version: '3.7'

services:

  # Data Lake storage
  localstack:
    image: localstack/localstack:2.1.0
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=test_key_id
      - AWS_SECRET_ACCESS_KEY=test_access_key
    ports:
      - "4566:4566"
    volumes:
      - ./compose/localstack:/etc/localstack/init/ready.d
      - ./datasets:/datasets
    healthcheck:
      test: [ "CMD", "awslocal", "s3", "ls" ]
      interval: 10s
      retries: 5
      start_period: 5s

  # Data Warehouse storage
  postgres:
    image: postgres:15.3
    environment:
      - POSTGRES_DB=data_warehouse
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./compose/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      start_period: 5s

  # Airflow metadata storage
  postgres_airflow:
    image: postgres:15.3
    environment:
      - POSTGRES_DB=airflow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5442:5432"
    volumes:
      - ./compose/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      start_period: 5s

  # Airflow for task orchestration
  airflow:
    build:
      context: ./projects/airflow
      dockerfile: Dockerfile
    depends_on:
      - postgres_airflow
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://postgres:password@postgres_airflow:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__PARALLELISM=4
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "airflow", "jobs", "check" ]
      interval: 10s
      retries: 5
      start_period: 10s

  # Proxy enabling Airflow to access the docker socket without root privileges
  docker-proxy:
    image: bobrik/socat
    command: "TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock"
    ports:
      - "2376:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: [ "CMD", "netstat", "-nlp", "|", "grep", ":2375" ]
      interval: 10s
      retries: 5
      start_period: 5s

  # Network debugging
  network-multitool:
    image: praqma/network-multitool:latest
    healthcheck:
      test: [ "CMD", "ping", "-c", "1", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 5s
