version: '3.7'
services:
  localstack:
    image: localstack/localstack:2.1.0
    environment:
      - SERVICES=s3
    ports:
      - "4566:4566"
    volumes:
      - ./compose:/etc/localstack/init/ready.d
      - ./datasets:/datasets
