version: '3.7'

services:

  # Data Lake storage
  localstack:
    image: localstack/localstack:2.1.0
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=test_key_id
      - AWS_SECRET_ACCESS_KEY=test_access_key
    ports:
      - "4566:4566"
    volumes:
      - ./compose/localstack:/etc/localstack/init/ready.d
      - ./datasets:/datasets
    healthcheck:
      test: ["CMD", "awslocal", "s3", "ls"]
      interval: 10s
      retries: 5
      start_period: 5s

  # Data Warehouse storage
  postgres:
    image: postgres:15.3
    environment:
      - POSTGRES_DB=data_warehouse
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./compose/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      start_period: 5s

  # Task orchestration
  airflow:
    build:
      context: ./compose/airflow
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: [ "CMD", "airflow", "jobs", "check" ]
      interval: 10s
      retries: 5
      start_period: 10s

  # Network debugging
  network-multitool:
    image: praqma/network-multitool:latest
    healthcheck:
      test: [ "CMD", "ping", "-c", "1", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 5s
